### ISSUE TITLE
Workflow to transform 2010 to 2020 geographies

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-factfinder#100]
2019 ACS data will be released in 2020 geographies.  Create workflow to transform 2019 ACS data from 2010 to 2020 geographies

**Comment by mgraber** [comment]
## Conversion formulas


(Estimate in 2020 CT) = (Estimate in 2010 CT) * (Ratio 2010 CT to 2020 CT)


As implemented:

If (Ratio 2010 CT to 2020 CT) = 1, then (MOE in 2020 CT) = (MOE in 2010 CT)
Else if (**Estimate in 2020 CT**) = 0, then (MOE in 2020 CT) = NULL
Else if ((Ratio 2010 CT to 2020 CT)^(0.56901))*7.96309 ≥ 100, then (MOE in 2020 CT) = (MOE in 2010 CT)
Else (MOE in 2020 CT) = (((Ratio 2010 CT to 2020 CT)^(0.56901))*7.96309)/100) * (**Estimate in 2010 CT**)


As written:

If (Ratio 2010 CT to 2020 CT) = 1, then (MOE in 2020 CT) = (MOE in 2010 CT)
Else if (**Estimate in 2010 CT**) = 0, then (MOE in 2020 CT) = NULL
Else if ((Ratio 2010 CT to 2020 CT)^(0.56901))*7.96309 ≥ 100, then (MOE in 2020 CT) = (MOE in 2010 CT)
Else (MOE in 2020 CT) = (((Ratio 2010 CT to 2020 CT)^(0.56901))*7.96309)/100) * (**MOE in 2010 CT**)

**Comment by SPTKL** [comment]
Notes for myself: 
- what to do with **percentage & percentage MOE** for profile only variables (we were taking p, z directly from census API instead of calculating)
-

**Comment by SPTKL** [comment]
implemented
