### ISSUE TITLE
Python package refactor

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#103]
# Brainstorming

## Download class
Purpose: make calls to census API
Methods: get_geoquery

## Convert class
Purpose: take data pulled from the download class and convert 2010 geographies to 2020 geographies if necessary

## Aggregate class
Purpose: calculate e & m for given geography and variable, using normal, median, or special methods

## Proportion class
Purpose: calculate p & z

## Clean class
Purpose: perform rounding and overwriting

**Comment by SPTKL** [comment]
```python
import importlib
AggregatedGeography = importlib.import_module(f'geography.{self.geography}.AggregatedGeography')
geography = AggregatedGeography()
```

for geography, we should have a different module for each year, so that we don't have to worry about lookup_geo.csv incompatibilities
![image](https://user-images.githubusercontent.com/13207770/118655023-24d88580-b7b7-11eb-8616-0f31f87ca5d1.png)
