### ISSUE TITLE
Errors in 2015-2019 ACS in 2020 Geogs

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#130]
### Other
- [x] Big m differences for `gprgcu18` across geographies, even with matching e
- [x] Big p and z differences for `lgchilep2` with matching e and m. Is base variable correct? We use `pop5pl2`.

### Poverty
- [x] Differences in z for `pu18bwpv`, `p65plbwpv` and `pbwpv` with matching c, e, m, p across most geographies
- [x] Difference in p for `p65plbwpv` for SI0305
- [x] Big differences in p for `pbwpv` for most NTA and CDTAs
- [x] Big differences in p for `pu18bwpv` for most NTA and CDTAs

### Medians #170
- [ ] Slight e differences for most tracts/NTA for `mdage`, large differences for CDTA MN64 and NTA MN6491
- [ ] Differences in `mdefftwrk` e of 1 for most tracts, CTDA, NTA. Big differences, but only for some tracts:
    - e: 36047006000, 36047012801, 36047033500, 36081018000 (all off by 5001)
    - m: 36047053700, 36005000100, 36061009600, 36047048000, 36061011202, 36061011900, 36081019901, 36081045200, 36047035200, and QN0151
- [ ] Differences in `mdemftwrk` e of 1 for most tracts, CTDA, NTA. Big differences, but only for some tracts:
    - e: 36005043501, 36047034000, 36047092800 (all off by 5001), and 36047091000 (off by 20001)
    - m: 36047035200, 36085013301, 36005014701, 36005003700
- [ ] Difference in `mdewrk` e of 1 for most tracts, CDTA, NTA. Large differences for BX27 and BX2791.
- [ ] Difference in `mdfaminc` e of 1 for most tracts, CDTA, NTA. Big differences, but only for some geographies:
    - e: 36081056100, QN0574
    - m: 36005002400, 36005003700, 36081019901, BX0991
- [ ] Difference in `mdgr` e of 1 for most tracts, CDTA, NTA. Big differences, but only for some geographies:
    - e: 36005027600, BX28, BX2891
    - m: BX0991, 36005002400, 36005030100, 36047061200, 36047069800, 36047073400, 36047075400, 36061011202, 36081026200, 36081040000, 36081040200, 36081043200, 36081043400, 36081045000, 36081045200, and more
- [ ] Difference in `mdhhinc` e of 1 for most tracts, CDTA, NTA. Big differences, but only for some geographies:
    - e: 36005027600, 36081056100, BX28, BX2891, QN0574
    - m: 36081005000
- [ ] Difference in `mdnfinc` e of 1 for most tracts, CDTA, NTA. Big differences, but only for some geographies:
    - e: 36005019400, 36005019900, 36047017400, 36047018800, 36047023200, 36047025000, 36047028501, 36047043200, 36081004001, 36081027600, and more
    - m: 36005031800, 36047023000, 36047046800, 36047047000, 36047064600, 36047069800, 36047074400, 36047084800, 36047096800, 36047102801, 36061009400, and more
- [ ] Difference in `mdvl` e of 1 for most tracts, CDTA, NTA. Big differences, but only for some geographies:
    - e: 36005018302, 36005019700, 36047028501 and more
    - m: 36005001901, 36005002702, 36005006000, 36005006500, 36005008600, 36005014500, 36047032100 and more

## For CT20-level data
- [x] Median variables have estimates exactly at the lower bound of a bin in cases where ratio = 1
        Walk through the workflow of calculating medians when the aggregation step does not combine records (1-to-1).
- [x] Median variables in sample have NULL p, ours currently has 100 #145 
- [x] MOE is rounded to different numbers of digits between our output and sample for several variables (e.g. `avghhsroc`)
- [x] Particularly large differences for non-special, non-median variables: `aghhinc`, `agip15pl`, `lgoeng1`, `lgoeng2`, `mv00t09`, `mv10ltr`, `mv90t99`, `pv150t174` (sample has all estimates of zero), 
- [x] We're treating several language vars (`lgoeng1`,`lgarblep1`, `lgchilep1`, etc.) as base variables, so p is 100. Sample data has p less than 100. #131 
- [x] Check on logic concerning which variables should have NULL moe by default.
    - [x] Several variables have NULL moe in sample data, while ours are non-NULL, even when estimates are non-zero (e.g. `blt10ltr` for some tracts). Why? https://github.com/NYCPlanning/db-acs-2020/pull/42
- [x] Check on logic for z calculation. In several cases, c, e, m, and p match exactly, but z differs.

**Comment by SPTKL** [comment]
1. median variables should have `p = NULL` and `z = NULL`

**Comment by SPTKL** [comment]
### Over all strategy
1. Check all cases where E != E_sample (across all geographies)
2. Check all cases where E = E_sample but M != M_sample
3. Check all cases where E = E_sample, M = M_sample but C != C_sample

**Comment by mgraber** [comment]
@SPTKL  given that there are also rounding errors, should we set a threshold for the 4 checks you list above?

**Comment by SPTKL** [comment]
> @SPTKL given that there are also rounding errors, should we set a threshold for the 4 checks you list above?

yeah, I remember we did 0.1 for previous iterations

**Comment by mgraber** [comment]
> median variables should have `p = NULL` and `z = NULL`
For some reason, median variables calculated at CT20 have p set to 100. The following line isn't working properly.
https://github.com/NYCPlanning/db-factfinder/blob/7da9fbeb6dabcd525b205501d0ea2d6260587cbf/factfinder/calculate.py#L233

**Comment by SPTKL** [comment]
> > median variables should have `p = NULL` and `z = NULL`
> 
> For some reason, median variables calculated at CT20 have p set to 100. The following line isn't working properly.
> https://github.com/NYCPlanning/db-factfinder/blob/7da9fbeb6dabcd525b205501d0ea2d6260587cbf/factfinder/calculate.py#L233

We would need to exclude median/special variables from this line

**Comment by SPTKL** [comment]
also it seems like `pv150t174` is just not calculated at all for a lot of the tracts, c,e,m,p,z all empty

**Comment by mgraber** [comment]
> > > median variables should have `p = NULL` and `z = NULL`
> > 
> > 
> > For some reason, median variables calculated at CT20 have p set to 100. The following line isn't working properly.
> > https://github.com/NYCPlanning/db-factfinder/blob/7da9fbeb6dabcd525b205501d0ea2d6260587cbf/factfinder/calculate.py#L233
> 
> We would need to exclude median/special variables from this line

@SPTKL  this line applied specifically to median variables

**Comment by EricaMaurer** [comment]
seems I skipped over pv150t174 in recalculating the data. it should not be blank. uploaded new version of economic file for this fix.

**Comment by EricaMaurer** [comment]
MOE for avghhsroc should be rounded to two decimal places. There's a few variables that have different logic for rounding than the normal rules. It was in the previous code logic

**Comment by EricaMaurer** [comment]
fixed MOE for blt10ltr (uploaded new housing file). are there others where this is an issue?

**Comment by mgraber** [comment]
> fixed MOE for blt10ltr (uploaded new housing file). are there others where this is an issue?

@EricaMaurer
Here is a list of variables that have non-zero tract-level estimates and NULL MOE in the sample data, with non-zero estimates and non-NULL MOE in our output. Several are inputs to median calculations. 

- e7pt5t10
- e10t12pt5
- e12pt5t15
- e15t17pt5
- e17pt5t20
- e20t22pt5
- e22pt5t25
- ern2pt5t5
- ern5t7pt5
- ernu2pt5k
- lgoenlep2
- mdage
- mdefftwrk
- mdemftwrk
- mdewrk
- mdfam
- mdfami10t14
- mdfami15t19
- mdfami20t24
- mdfami25t29
- mdfami30t34
- mdfami35t39
- mdfami40t44
- mdfami45t49
- mdfami50t59
- mdfami60t74
- mdfami75t99
- mdfami200pl
- mdfaminc
- mdfamiu10
- mdfi100t124
- mdfi125t149
- mdfi150t199
- mdgr
- mdhhi10t14
- mdhhi15t19
- mdhhi20t24
- mdhhi25t29
- mdhhi30t34
- mdhhi35t39
- mdhhi40t44
- mdhhi45t49
- mdhhi50t59
- mdhhi60t74
- mdhhi75t99
- mdhhi200pl
- mdhhinc
- mdhhiu10
- mdhi100t124
- mdhi125t149
- mdhi150t199
- mdnfinc
- mdpop0t4
- mdpop5t9
- mdpop10t14
- mdpop15t17
- mdpop18t19
- mdpop20
- mdpop21
- mdpop22t24
- mdpop25t29
- mdpop30t34
- mdpop35t39
- mdpop40t44
- mdpop45t49
- mdpop50t54
- mdpop55t59
- mdpop60t61
- mdpop62t64
- mdpop65t66
- mdpop67t69
- mdpop70t74
- mdpop75t79
- mdpop80t84
- mdpop85pl
- mdpop_3
- mdrms
- mdvl
- nf100t124
- nf125t149
- nf150t199
- nfam
- nfi200pl
- nfmi10t14
- nfmi15t19
- nfmi20t24
- nfmi25t29
- nfmi30t34
- nfmi35t39
- nfmi40t44
- nfmi45t49
- nfmi50t59
- nfmi60t74
- nfmi75t99
- nfmiu10
- oochu5
- ov1t149m
- ov2milpl
- ov100t124
- ov125t149
- ov150t174
- ov150t199m
- ov175t199
- ov200t249
- ov250t299
- ov300t399
- ov400t499
- ov500t749
- ov750t999
- ovl10t14
- ovl15t19
- ovl20t24
- ovl25t29
- ovl30t34
- ovl35t39
- ovl40t49
- ovl50t59
- ovl60t69
- ovl70t79
- ovl80t89
- ovl90t99
- ovlu10
- r1kt1249
- r1p5t1999
- r2kt2499
- r2p5t2999
- r3kt3499
- r100t149
- r150t199
- r200t249
- r250t299
- r300t349
- r350t399
- r400t449
- r450t499
- r500t549
- r550t599
- r600t649
- r650t699
- r700t749
- r750t799
- r800t899
- r900t999
- r1250t1p5
- r3500pl
- roccshrnt
- ru100
- wrke16pl

**Comment by EricaMaurer** [comment]
the variables that aren't shown in the profile and are just used as inputs to medians do not use MOEs so didn't previously calculate those columns. ok to calculate them on your end though.

the variables included in the list that are medians that have estimates but no MOE shown was because our median calculations produced an error or the data is top-coded

just fixed LgOEnLEP1M and reuploaded the social part 2 file

I think that should clear everything unless I missed one on the list that doesn't fall into those categories

**Comment by mgraber** [comment]
> the variables that aren't shown in the profile and are just used as inputs to medians do not use MOEs so didn't previously calculate those columns. ok to calculate them on your end though.
> 
> the variables included in the list that are medians that have estimates but no MOE shown was because our median calculations produced an error or the data is top-coded
> 
> just fixed LgOEnLEP1M and reuploaded the social part 2 file
> 
> I think that should clear everything unless I missed one on the list that doesn't fall into those categories

@EricaMaurer  I tried sorting in the comment above. For cases where your median calculation showed an error or the data was top-coded, what should we be producing?

**Comment by EricaMaurer** [comment]
-- Big m differences for gprgcu18 across geographies, even with matching e... found the error on my end-- was referencing the wrong column. Will re-upload sample data.

--Big p and z differences for lgchilep2 with matching e and m. Is base variable correct? We use pop5pl2... base should be LgOenLEP2

-- Differences in z for pu18bwpv, p65plbwpv and pbwpv with matching c, e, m, p across most geographies
check base variable in formula...
---pu18bwpv -- base: PU18PvU
---p65plbwpv -- base: P65plPvU
---pbwpv -- base: PopPvU1

-- Difference in p for p65plbwpv for SI0305... weird that only one geog would be off
= (175.075265017668/2487.45653710247)*100 = 7.03832458602895
rounded: 7.0

-- Big differences in p for pbwpv for most NTA and CDTAs... check base: PopPvU1 (should be ok if percent for tracts match)

-- Big differences in p for pu18bwpv for most NTA and CDTAs: check base: PU18PvU (should be ok if percent for tracts match)

--  MOE is rounded to different numbers of digits between our output and sample for several variables (e.g. avghhsroc)
--- estimate and MOE should be rounded to same number of digits. Below are variables that are not rounded to full number (number of decimal digits) 
--- mdage: 1
--- avghhsz: 2
--- avgfmsz: 2
--- mntrvtm: 1
--- hovacrt: 1
--- rntvacrt: 1
--- mdrms: 1
--- avghhsooc: 2
--- avghhsroc: 2

**Comment by SPTKL** [comment]
@mgraber do you think we can close this issue and open up a new one just for the medians? it seems like all the non-median related issues are resolved
