### ISSUE TITLE
Check where E != E_sample (across all geographies)

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#132]
## Tract split example
In this example, tract 36061007000 is split into 36061007001 and 36061007002, with ratios 0.46658 and 0.53342.
```sql
SELECT
	a.labs_geoid,
	a.census_geoid,
	a.pff_variable,
	a.e as e_python,
	b.e as e_erica,
	a.e - b.e as e_diff,
	(a.pff_variable IN ('mdage', 'mdhhinc', 'mdfaminc', 'mdnfinc', 'mdewrk', 'mdemftwrk', 'mdefftwrk', 'mdrms', 'mdvl', 'mdgr')) AS median_var,
	(a.pff_variable IN ('percapinc', 'mntrvtm', 'mnhhinc', 'avghhsooc', 'avghhsroc', 'avghhsz', 'avgfmsz', 'rntvacrt', 'hovacrt', 'wrkrnothm')) AS special_var,
	(a.pff_variable IN ('pop1pl', 'hu1', 'p65plpvu', 'pop3plen', 'lgolg1', 'och6t17', 'lgruspol1', 'ochu5', 'ms_m15pl', 'cvem16pl2', 'mdage', 'hovacrt', 'popu18_2', 'lgoenlep2', 'lgkor1', 'ochuprnt1', 'hu2', 'ochu6', 'lgarab1', 'lgoeng1', 'hsp2', 'cni1864_1', 'uem', 'fb3', 'lgchilep1', 'rntvacrt', 'vacsoldno', 'pop_1', 'mdhhinc', 'lgviet1', 'ochuprnt2', 'cvlf2', 'mdvl', 'lgbase', 'mdfaminc', 'mdemftwrk', 'nan', 'oochu2', 'median', 'fb2', 'vacrntno', 'pop_5', 'hh3', 'cvnipop1', 'mdnfinc', 'rate', 'hu3', 'pop5pl1', 'fam2', 'ochu2', 'ochu4', 'mntrvtm', 'cvem16pl4', 'poppvu1', 'pop16pl', 'pop_4', 'owneroccbase', 'nlf2', 'lgtag1', 'fampvu', 'lgsp1', 'cvniu18_2', 'pu18pvu', 'cvnipop2', 'pop', 'pop5pl2', 'avghhsooc', 'oochu3', 'mean', 'renteroccbase', 'ochu3', 'fb4', 'mdgr', 'cvem16pl3', 'avghhsroc', 'hh1', 'avghhsz', 'mdewrk', 'dfhs2', 'lggrm1', 'cvlfem', 'lgoasn1', 'occbaseunits', 'nfam2', 'percapinc', 'cvni65pl', 'hu4', 'mdefftwrk', 'hunomrtg2', 'wrkr16pl', 'f16pl', 'ms_f15pl', 'pop65pl2', 'asn1rc', 'cvpop18pl', 'ea_p25pl', 'huwmrtgex', 'cvniu18_1', 'lgoieu1', 'lgfr1', 'gplgcu18', 'pop_2', 'mnhhinc', 'lgarblep1', 'hh2', 'avgfmsz', 'poppvu2', 'lgchi1', 'hhpop')) AS base_var
FROM pff_acs."test-2019" a
FULL OUTER JOIN pff_acs."sample-2019" b
ON a.labs_geoid = b.labs_geoid
AND a.pff_variable = b.pff_variable
WHERE a.geotype = 'CT20'
AND a.census_geoid IN ('36061007001', '36061007002')
AND a.e - b.e IS NOT NULL
ORDER BY pff_variable;
```
Variables with estimate discrepancies are:
- `aghhinc` (over- and under-estimate of the same magnitude) Fixed by #135 
- `agip15pl` (over- and under-estimate of the same magnitude) Fixed by #135 
- `mdage` (likely due to rounding, difference is small)
- `mdefftwrk` (over-estimates)
- `mdewrk` (over-estimates)
- `mdgr` (over-estimates)
- `mdhhinc` (over-estimates)
- `mdnfinc` (over-estimates)
- `mdvl` (over-estimates)
- `mv00t09` (over-estimates) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `mv10ltr` (under-estimates) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `mv90t99` (over-estimates) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `prvwswrkr` (over- and under-estimate of the same magnitude, only 1 off) Fixed by #135 
- `pv150t174` (over-estimates) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/38
- `lgoeng1` (over-estimates) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/40
- `lgoeng2` (over-estimates) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/40

For values see [tract_split_diffs.csv](https://github.com/NYCPlanning/db-factfinder/files/6785663/tract_split_diffs.csv)

## Tract merge example
In this example, 36005014400 is a combination of 0.98013 of 36005011000 and all of 36005014400.

Variables with estimate discrepancies are:
- `mv00t09` (over-estimate) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `mv10ltr` (under-estimate) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `mv90t99` (over-estimate) Fixed by https://github.com/NYCPlanning/db-factfinder/pull/137
- `pv150t174` (over-estimate) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/38

For values see [tract_merge_diffs.csv](https://github.com/NYCPlanning/db-factfinder/files/6785670/tract_merge_diffs.csv)

## One-to-one example
In this example, 36005000100 neither splits nor merges and ratio = 1.

Variables with estimate discrepancies are:
- `lgoeng1` (slight over-estimate) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/40
- `lgoeng2` (slight over-estimate) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/40
- `lgoenlep2` (over-estimate) Fixed by https://github.com/NYCPlanning/db-acs-2020/pull/40

For values see [no_change_diffs.csv](https://github.com/NYCPlanning/db-factfinder/files/6785677/no_change_diffs.csv)

## All differences
```sql
SELECT
	a.labs_geoid,
	a.census_geoid,
	a.pff_variable,
	a.e as e_python,
	b.e as e_erica,
	a.e - b.e as e_diff
FROM pff_acs."test-2019" a
FULL OUTER JOIN pff_acs."sample-2019" b
ON a.labs_geoid = b.labs_geoid
AND a.pff_variable = b.pff_variable
ORDER BY ABS(a.e - b.e) DESC;

-- Or use:
WITH compare AS (
SELECT
	a.labs_geoid,
	a.census_geoid,
	a.geotype,
	a.pff_variable,
	a."domain",
	a.c as c_sample, b.c as c_ff, b.c-a.c as c_diff,
	a.e as e_sample, b.e as e_ff, b.e-a.e as e_diff,
	a.m as m_sample, b.m as m_ff, b.m-a.m as m_diff,
	a.p as p_sample, b.p as p_ff, b.p-a.p as p_diff,
	a.z as z_sample, b.z as z_ff, b.z-a.z as z_diff
FROM pff_acs."sample-2019" a
JOIN pff_acs."test-2019" b
ON a.labs_geoid = b.labs_geoid
AND a.geotype = b.geotype
AND a.pff_variable = b.pff_variable)

SELECT *
FROM compare
WHERE e_diff > 0.1 AND e_diff IS NOT NULL;
```

## Possible sources of discrepancies
- Inputs:
    - CLI variable lookup
    - Metadata mapping census variables to pff_variables
        - Which variables are base variables 
    - Metadata for median variables
    - Metadata for special variables
    - Tract to tract relationships
    - Ratio values
    - Relationship between 2020 census tracts, 2020 CDTA and 2020 NTA
- Methodology:
    - How to handle median and special variables when one-to-one
    - How to handle median and special variables when split or merged
    - When to clean values of m, p, z to NULL
    - Formula for calculating converted estimate
    - Formula for calculating converted MOE

**Comment by EricaMaurer** [comment]
re-uploaded social part 2-- was missing a column of data in each so your output was correct

**Comment by EricaMaurer** [comment]
It looks like the references may be off for the moved variables.
36005011000 is 0 for each of the categories so even though it's combined with 36005014400 the end result should equal the values from 36005014400

mv00t09: DP04_0054
mv10ltr: DP04_0051+DP04_0052+DP04_0053
mv90t99: DP04_0055

**Comment by mgraber** [comment]
@EricaMaurer I will update the reference columns for those variables. Thanks!

**Comment by mgraber** [comment]
Remaining issues are primarily medians, so we need to double check [input variables, design factors, and associated ranges](https://github.com/NYCPlanning/db-factfinder/blob/dev/factfinder/data/acs/2019/median.json).
