### ISSUE TITLE
Check where E = E_sample but M != M_sample

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#139]
gprgcu18 has MOE discrepancies across most geographies, even with matching estimates.

In the python code, logic for setting MOE of zero estimates is:
https://github.com/NYCPlanning/db-factfinder/blob/ecdd48d0e069611bb790810507985e7a24dad8a0/factfinder/calculate.py#L320-L326
MOE of zero estimates for variables that are not base variables is set to null. MOE of zero estimates for variables that are base variables is set to zero.

For the following variables, sample has zero-estimate but non-zero MOE, python results in 0 MOE (excludes median inputs).

abroad
afghan
afr
african
agffhm
aiannh
alb
albania
amercn
arab
arabsub
armenian
artenrafs
asia
asn1rc
asn2pl
asnbng
asnchinot
asneast
asnflp
asnind
asnjpn
asnkor
asnlao
asnnh
asnoasn
asnpak
asnseast
asnsouth
asnsril
asnthai
asntwn
asnvtn
austria
austrian
austrln
belarus
belgian
belgium
belizean
blnh
blt00t09
blt10ltr
blt40t49
blt50t59
blt60t69
blt70t79
blt80t89
blt90t99
bltbf39
bngldsh
brbdian
british
brtwind
brzlian
c1864damb
c1864dcog
c1864dhrg
c1864dild
c1864dscr
c1864dvsn
c65pldamb
c65pldcog
c65pldhrg
c65pldild
c65pldscr
c65pldvsn
canadian
carprusn
china
chnohktwn
cni18t64d
constctn
croatian
cu18damb
cu18dcog
cu18dscr
cu18dvsn
cvem16pl1
cvem16pl2
cvem16pl3
cvem16pl4
cvlf1
cvlf18t64
cvlf2
cvlfem
cvlfuem1
cvlfuem2
cvni65pl
cvni65pld
cvnid
cvnid_amb
cvnid_cog
cvnid_hrg
cvnid_ild
cvnid_scr
cvnid_vsn
cvniu18_1
cvniu18_2
cvniu18d
cvrdean
cvvet18pl
cw_crpld
cw_drvaln
cw_oth
cw_pbtrns
cw_wlkd
cw_wrkdhm
cypriot
czchslv
czech
danish
denmark
dfhsdfcnt
dfhssmcnt
dfhsus
dhdfcntnyc
dhnonyc
dutch
ea_9t12nd
ea_ascd
ea_bchd
ea_bchdh
ea_grdpfd
ea_hscgrd
ea_lt9g
ea_lthsgr
ea_sclgnd
easia
edhlthcsa
eeur
eeurpn
egyptn
emhins
emnhins
empbhins
empvhins
eng
english
engonly1
engonly2
ethpian
eur
european
f16pl
f16plclfe
f16plcvlf
f16pllf
fam1
fam2
fam3
fambwpv
famchu18
fami10t14
fami15t24
fami200pl
fami25t34
fami35t49
fami50t74
fami75t99
famiu10
fampvu
fb1
fb2
fhns
fhnschu18
fi100t149
fi150t199
finnish
fire
fpop0t5
fpop10t14
fpop15t19
fpop20t24
fpop25t29
fpop30t34
fpop35t39
fpop40t44
fpop45t49
fpop50t54
fpop55t59
fpop5t9
fpop60t64
fpop65t69
fpop70t74
fpop75t79
fpop80t84
fpop85pl
france
frcandian
frnotbsq
german
germany
ghanaian
gplgcu18
gprgcu18
gr15kt19k
gr1kt14k
gr20kt24k
gr25kt29k
gr3kpl
gr500t999
greece
greek
grnorntpd
grpi15t19
grpi20t24
grpi25t29
grpi30t34
grpi35pl
grpi50pl
grpintc
grpiu15
gru500
guyanese
gvtwrkr
haitian
hgrian
hh1
hh1pl65pl
hh1plu18
hh2
hh3
hh4
hh5
hhcomp
hhi10t14
hhi15t24
hhi200pl
hhi25t34
hhi35t49
hhi50t74
hhi75t99
hhint
hhiu10
hi100t149
hi150t199
hongkong
hovacu
hsp1
hsp2
hspalloth
hsparg
hspcam
hspcol
hspcr
hspcub
hspdom
hspec
hspguatm
hsphnd
hspme
hspnic
hspoth
hsppan
hspperu
hsppr
hspprg
hspsalv
hspsam
hspspnrd
hspspnsh
hspvnz
hu1
hu10t19u
hu1ua
hu1ud
hu2
hu20plu
hu2u
hu3
hu3t4u
hu4
hu5t9u
hungary
hunomrtg1
hunomrtg2
huwmrtg
huwmrtgex
inc_cpba
inc_rtrmt
inc_snap
inc_sosec
inc_spsec
india
info
iran
iranian
ireland
irish
israeli
italian
italy
jamaican
japan
jrdnian
korea
kzkhstan
laos
lebanese
lf
lfarmdf
lgarab1
lgarab2
lgarblep1
lgarblep2
lgchi1
lgchi2
lgchilep1
lgchilep2
lgfr1
lgfr2
lgfrlep1
lgfrlep2
lggrm1
lggrm2
lggrmlep1
lggrmlep2
lgkor1
lgkor2
lgkorlep1
lgkorlep2
lgoanlep1
lgoanlep2
lgoasn1
lgoasn2
lgoenlep2
lgoielep1
lgoielep2
lgoieu1
lgoieu2
lgolg1
lgolg2
lgolglep1
lgolglep2
lgrsplep1
lgrsplep2
lgruspol1
lgruspol2
lgsp1
lgsp2
lgsplep1
lgsplep2
lgtag1
lgtag2
lgtaglep1
lgtaglep2
lgvielep1
lgvielep2
lgviet1
lgviet2
lthian
lthuania
mdhh
mgbsciart
mhns
mhnschu18
mnfctrng
mobhm
mpop0t5
mpop10t14
mpop15t19
mpop20t24
mpop25t29
mpop30t34
mpop35t39
mpop40t44
mpop45t49
mpop50t54
mpop55t59
mpop5t9
mpop60t64
mpop65t69
mpop70t74
mpop75t79
mpop80t84
mpop85pl
mrdchu18
mrdfam
ms_f15pl
ms_fdvcd
ms_fmrdsp
ms_fnvmrd
ms_fsp
ms_fwd
ms_m15pl
ms_mdvcd
ms_mmrdsp
ms_mnvmrd
ms_msp
ms_mwd
mv00t09
mv10ltr
mv90t99
mvbf89
neur
neurpn
nfam1
nfam2
nfama
nfama65pl
nhins
nigerian
nlf1
nlf2
nlfhins
nlfnhins
nlfpbhins
nlfpvhins
nmsmp1014
nmsmp1519
nmsmp2024
nmsmp2529
nmsmp3034
nmsmp35pl
nmsmpntc
nmsmpu10
norwgian
novhclav
nrcnstmnt
nthrlds
ntvnotnys
ntvprusab
nzealnd
oarab
oc6t17plf
och6t17
ochu1
ochu2
ochu3
ochu4
ochu5
ochu6
ochu6plf
ochuprnt1
ochuprnt2
ocpr0t1
ocpr1p5pl
ocpr1pl
oeeur
oochu1
oochu2
oochu3
oochu4
osubsafr
othnh
othnotpa
owasia
oweur
owind
p65plbwpv
p65plpvu
pakistan
pbwpv
philipns
poland
polish
pop10t14
pop15t19
pop20t24
pop25t29
pop30t34
pop35t39
pop3plen
pop40t44
pop45t49
pop50t54
pop55t59
pop5t9
pop60t64
pop65pl1
pop65pl2
pop65plf
pop65plm
pop65t69
pop70t74
pop75t79
pop80t84
pop85pl
popoochu
popu181
popu18_2
popu18f
popu18m
popu5
portgese
prdtrnsmm
prfsmgawm
prvwswrkr
pu18bwpv
pu18pvu
pubadmin
pv100t124
pv125t149
pv150t174
pv175t184
pv185t199
pv200t299
pv300t399
pv400t499
pv500pl
pv50t74
pv75t99
pvhins
pvu50
rc2plnh
retail
rntvacu
rochu1
rochu2
romania
romanian
rshp_ch
rshphhldr
rshp_nr
rshp_nrup
rshp_othr
rshp_sp
rshp_ssup
russia
russian
salesoff
saudiar
scandnvn
scasia
scot
scottish
sctchirsh
seasia
se_clggsc
se_g1t8
se_g9t12
se_kndgtn
se_nscpsc
serbia
serbian
seur
slavic
slfemninc
slovak
smp20t24
smp25t29
smp30t34
smp35pl
smpntc
smpu20
sngapore
snglese
spain
srilanka
srvc
subsaf
sudanese
sweden
swedish
swiss
switzrld
taiwan
tandtob
thailand
trwhut
turkey
turkish
u18nhins
uem
uemhins
uemnhins
uempbhins
uempvhins
uknoengsc
ukraine
ukrnian
unclsnr
untdkgdm
updfmwrkr
uzbkstan
vachu
vacrnt
vacrntno
vacsale
vacsoldno
vhcl1av
vhcl2av
vhcl3plav
vietnam
vl100t149
vl150t199
vl1milpl
vl200t299
vl300t499
vl500t999
vl50t99
vlu50
wasia
welsh
weur
whlsale
windnhsp
windsub
wrkr16pl
wrkrnothm
wtnh
yemen
yugoslv

**Comment by EricaMaurer** [comment]
When some geographies are split the estimate is less than 1 but greater than 0 so the MOE is calculated. When we round the data, the estimate then appears as a zero but the MOE still exists. We will change this so the same logic is used-- when an estimate is zero, all other columns of data (m,c,p,z) are null
