### ISSUE TITLE
Include city and boro level data in 2019 test file

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#141]

**Comment by mgraber** [comment]
We need to include other 2010 options like we do tracts:
https://github.com/NYCPlanning/db-factfinder/blob/5f221963cab0ee42e5f1c567b732be794cb6fa28/factfinder/geography/2010_to_2020.py#L176-L177

**Comment by SPTKL** [comment]
but city2010 = city2020, I don't think we care about the year on city and boro

**Comment by mgraber** [comment]
Change to 2020 based on teams conversation with population for display consistency.
