### ISSUE TITLE
Missing geotypes in new 2019 release schema

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/db-factfinder#142]
The app expects _at least_ these types:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/5004319/125122891-dd7dbf80-e0aa-11eb-81f2-7b4c8c5a932c.png">

But the new 2019 data output seems to only include these geotypes:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/5004319/125123007-fc7c5180-e0aa-11eb-8d9e-204c95194bd4.png">

More may need to be included, but city and borough are necessary for the app to work correctly.

(Note: these seem to be available in "sample-2019" table)

**Comment by SPTKL** [comment]
#141
