### ISSUE TITLE
Add missing median logic case: same bin, first non-zero

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#187]

**Comment by SPTKL** [comment]
median moe cases:
> between bin = not the top/bottom bin
- p_lower and p_upper in same bin
   - the bin is the top bin
   - the bin is the bottom bin
   - the bin is a between bin
-  p_lower and p_upper in different bin
   - p_lower in top bin
   - p_lower in bottom bin 
   - p_lower in a between bin

**Comment by mgraber** [comment]
#188
