### ISSUE TITLE
Additional info in Metadata

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#193]
## Current data structure:
```json
    {
        "pff_variable": "fam1",
        "census_variable": [
            "DP02_0002"
        ],
        "base_variable": "hh1",
        "domain": "social",
        "rounding": 0,
        "source": ""
    },
```
the field `source` is not used, we should consider retire

## Proposed schema:
```json
    {
        "pff_variable": "fam1",
        "census_variable": [
            "DP02_0002"
        ],
        "base_variable": "hh1",
        "domain": "social",
        "rounding": 0,
        "category": "Household Type",
    },
```
we are actually just replacing source with category, there's no indication that labs is using `unittype`, `notinprofile`

**Comment by SPTKL** [comment]
missing variables?
- all language variables
- MHnW	ACS	2006-2010, 2013-2017	Social	Household Type		HH1	basic	NA	
MHnWChU18	ACS	2006-2010, 2013-2017	Social	Household Type		HH1	basic	NA	
FHnH	ACS	2006-2010, 2013-2017	Social	Household Type		HH1	basic	NA	
FHnHChU18	ACS	2006-2010, 2013-2017	Social	Household Type		HH1	basic	NA	
- Mv80t89	ACS	2013-2017	Housing	Year Householder Moved Into Unit		OcHU3	basic	NA	
MvBf79	ACS	2013-2017	Housing	Year Householder Moved Into Unit		OcHU3	basic	NA

**Comment by mgraber** [comment]
@SPTKL should we also modify the metadata in median.json to contain top/bottom coding values?
