### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-factfinder#206]
Consistent terms for:
1. What we call the bin/range/etc., which is itself a variable that represents the number of people/household with a characteristic falling between two values (i.e. population ages 9 to 15). So far I've used bin. Our code refers to these as both bins and ranges.
> I think bin works.  Perhapes note in the documentation that in the code bin and range are synonymous, and just define bin.

2. What we call the values associated with bin boundaries. For example, if a bin is pop ages 9 to 15, what term do we use to refer to the numbers 9 and 15?
> top bin value and bottom bin value?

3. What we call the number that represents the population within each bin. For example, if there are 200 people ages 9 to 15, what term do we use to refer to the number 200? Amanda Doyle (DCP) this goes to your confusion about "units" and "values". To me, "values" sounded like it was referring to 9 or 15 in this example, rather than 200.
> Ah I see.  I'd describe that as the total count for the bin, which is long, but I think if you define "units" then using units would work.

4. What we call the boundaries formed by adding and subtracting 1 SE from 50%. In our code, these boundaries are p_lower and p_upper. We need to be able to differentiate this from the confidence interval we form around the median itself.
> 

5. What we call the total population in every bin. In our code, this is represented both by N (implying "total population") and B (implying "base").
> "units"?

6. What we call the bins containing p_lower and p_upper.
> 

7. What we call the boundaries of the confidence interval around the median (the results of calling get_bound). We need to distinguish this from the boundaries around the 50% value, formed by adding and subtracting 1SE.
>

**Comment by SPTKL** [comment]
3. I would prefer count, it makes more intuitive sense to me
4. not sure
5. N = B right? 
6. lower_bin and upper_bin

**Comment by mgraber** [comment]
@SPTKL I don't know how to translate the reasoning behind p_lower/p_upper into plain English without acknowledging that they're boundaries of a 1SE interval around the 50% value.
