### ISSUE TITLE
Git ignore `.output`

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-factfinder#228]
Most of our data products have `.output` ignored by git as we don't want to be pushing/pulling cached data when we can avoid it

**Comment by mbh329** [comment]
@SashaWeinstein this would be an easy thing to close out

**Comment by SashaWeinstein** [comment]
I've got orders from Amanda to only work on transition and the A2 PR, this will have to be addressed by another engineer 😢
