### ISSUE TITLE
Ingest non inflated data needs to be used for 2006-2010

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-factfinder#236]
The 2006-2010 economic and housing need to be changed out with the not inflated data and we should be all set.  Source data is in Non_Inflated tabs in spreadsheet that I forwarded from Pop on Tue 7/5/2022 at 4:18 PM

**Comment by SashaWeinstein** [comment]
I can implement this change while pluto builds on my machine and I can't use my 5432 port for devDB
