### ISSUE TITLE
2021 ACS Metadata missing `category` field.

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/db-factfinder#254]
I was debugging an issue that Population found while testing the new ACS data in PFF and I have hunch that the root cause is that the [metadata file](https://github.com/NYCPlanning/db-factfinder/blob/main/factfinder/data/acs/2021/metadata.json) for the 2021 ACS data is missing the `category` field. Our scripts download those metadata.json files and use them to associate rows with each other in our app. The metadata file for [2010](https://github.com/NYCPlanning/db-factfinder/blob/main/factfinder/data/acs/2010/metadata.json) still has them and I don't think they've changed. Is is possible to add that field back to 2021 metadata? Thanks!

**Comment by damonmcc** [comment]
per PR https://github.com/NYCPlanning/db-factfinder/pull/252, `2021/metadata.json` was provided by the Population team. not sure how they generated it, I'll reach out

**Comment by damonmcc** [comment]
I generated it 🤦🏾‍♂️ by converting the excel file provided by Population to json. have received a new excel file and will regenerate json file
