### ISSUE TITLE
Questions for Population Div

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#41]
# New questions

# Archived questions
1. #73 `hh5` and `pop_6`
     -  The variables hh5 and hh2 are use the same census variable, but different base. The base for hh5 is mnhhinc, which relies on the E and M of both hh5 and hh2. hh5 is not displayed in the app. We are seeing same E, M, P but different Z for hh5. 
     - Similarly, pop_6 and pop use the same census variable, but pop_6 has percapinc as a base. The special calculation for percapinc relies on the E and M of pop6. We are seeing same E, M, P but different Z for pop6. 
> HH5 and Pop_6 should not be assigned a base of the special variables (which is creating incorrect calculation results), except to note that they are used as inputs for these calculations.
2. #77 Should we still calculate P and Z for NotinProfile variables? If not, this resolves question 1.
> If not calculated in previous versions, do not calculate now.
3. We rely on a geo-lookup relating census geographies (blocks) to city geographies (CDs, NTAs, Council districts, and -- at least until they're deprecated -- PUMAs).  Where should we get this data from in the future and on what update cycle?
4. #43 What should we use as the new pff variable names, now that language data is categorized?

5. If a variable is not a base variable and the estimate is 0, then we set the MOE to null. Why can’t non-base zero-estimates have non-zero MOE?

6. If a variable is a base variable, the estimate is 0, and the calculated MOE is missing, then we set the MOE to 0. Why do we do this rather than keeping it as null?  #40

7. If a variable has a zero estimate, we set both the proportion (p) the MOE of the proportion (z) to null. Why not p=0, assuming the base variable is not 0?

8. Borough- and city-level base variables with missing MOE get MOEs set to 0. This seems like a more general case of question 2, where now it doesn’t matter if the estimate is non-zero. Why do we do this, rather than keeping them as null? And why does this only apply for those two spatial units?

9. Similarly, borough- and city-level base variables with missing CV get CV set to 0. Why do we do this, rather than keeping them as null? And why does this only apply for those two spatial units?

10. Borough- and city-level base variables have the proportions (p) set to 100, and the proportion MOE (z) set to null. This makes sense since base-variables serve as their own denominators in a proportion calculation. Why does this only apply to those two spatial units?

> AD notes from meeting addressing these questions
> 1 - visualization thing - in PFF anything that's an estimate of 0 show up as NULL because we don't know if 0 is precise 0.  Census B - if estimate is 0 MOE is 0 / NULL for calculation
> 2 - see answer to question 1.  Don't want to inflate MOE with standard value from Census (i.e. 11)
> 3 - fine to show it as 0.  Currently, all associated data with a 0 estimate is blank.  "Grandfathered in"
> 4 - Control totals at borough and city level.  ***** becomes 0 
> 5 - Because MOE is 0 set CV to 0 (control total)
> 6 - All geographies.  Anytime there is a base variable percent is set to 100 and MOE is 0

**Comment by AmandaDoyle** [comment]
AD notes
1 - visualization thing - in PFF anything that's an estimate of 0 show up as NULL because we don't know if 0 is precise 0.  Census B - if estimate is 0 MOE is 0 / NULL for calculation
2 - see answer to question 1.  Don't want to inflate MOE with standard value from Census (i.e. 11)
3 - fine to show it as 0.  Currently, all associated data with a 0 estimate is blank.  "Grandfathered in"
4 - Control totals at borough and city level.  5* becomes 0 
5 - Because MOE is 0 set CV to 0 (control total)
6 - All geographies.  Anytime there is a base variable percent is set to 100 and MOE is 0
