### ISSUE TITLE
lgoenlep1 - language spoken at home -> no longer available through census API since 2018

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#43]
## Status: pending ... need Population input

this variable is used by community profiles and population factfinder, we have rules to backfill variables that are no longer produced using an older version of the data
https://github.com/NYCPlanning/db-acs/blob/834b15dd77ba330ac526f886df701c1d313b71ca/06_dataloading.py#L53-L63

**Comment by mgraber** [comment]
Population division requests that we transition to using the collapsed table, [C16001](https://data.census.gov/cedsci/table?q=New%20York%20languages&g=0400000US36&tid=ACSDT5Y2018.C16001), for these fields.

**Comment by mgraber** [comment]
#97
