### ISSUE TITLE
p65plbwpv, and pu18bwpv, pbwpv  e, m, p match, but z not matching

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#72]
maybe these two shouldn't be part of profile only variable exception?
#69 
#23 
#56

**Comment by mgraber** [comment]
Also true for `pbwpv`

**Comment by SPTKL** [comment]
I did some spot checks and don't see obvious errors

**Comment by mgraber** [comment]
For these variables, P and Z come from a different table than E and M.

> - [x] PBwPv
> -- percent: S1701_C03_001E
> -- percent MOE: S1701_C03_001M
> - [x] PU18BwPv
> -- percent: S1701_C03_002E
> -- percent MOE: S1701_C03_002M
> - [x] P65plBwPv
> -- percent: S1701_C03_010E
> -- percent MOE: S1701_C03_010M
> 

_Originally posted by @EricaMaurer in https://github.com/NYCPlanning/db-acs/issues/28#issuecomment-584768066_

**Comment by SPTKL** [comment]
maybe we should create them as variables in the metadata? pbwpvp, pbwpvz & etc, then somehow merge them somewhere?
