### ISSUE TITLE
Do not calculate P and Z for NotinProfile variables

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#77]
if a variable is not in profile, we should just ignore the calculation of P and Z (since only E, M are relevant)? 
> No, see #41

**Comment by mgraber** [comment]
Lookup for in-profile variables for all vars included in 10, 17, 18.
[meta_in_profile.csv](https://github.com/NYCPlanning/db-factfinder/files/6540620/meta_in_profile.csv)
