### ISSUE TITLE
Base variable calculation

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#8]
for each variable, we would also need to calculate the base variable (e, m)  so that we can calculate p, z
However note that, for some variables, we can get p and z directly from census by querying `XXXXX_01PE` or `XXXXX_01PM`

**Comment by mgraber** [comment]
Potential functions 
```python
def calculate_base(self, pff_variable, geotype) -> pd.DataFrame:
    """
    Gets base from metadata then calls calculate_variable(self, base_variable, geotype) 
   """

```

**Comment by SPTKL** [comment]
implemented
