### ISSUE TITLE
Implement outlier check

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-factfinder#9]
depends on the variable, outlier can be
555555555
888888888
333333333 & etc 

and depends on if the variable contains an outlier default value, we would have to NULL out other values (m, c, p, z)
https://github.com/NYCPlanning/db-acs/blob/834b15dd77ba330ac526f886df701c1d313b71ca/02_nta.py#L8-L10

**Comment by mgraber** [comment]
#18

**Comment by SPTKL** [comment]
implemented
