### ISSUE TITLE
Median & special variables for aggregated geotypes return multiprocessing error

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#93]
Relevant for community profiles floodplain variables.
This error comes from:
https://github.com/NYCPlanning/db-factfinder/blob/dc75b1818c7a2c5c3f7e47fe69e8ef97232d3c2e/factfinder/main.py#L225-L227
Error: `AssertionError: daemonic processes are not allowed to have children`

**Comment by SPTKL** [comment]
resolved
